-- Run this in Supabase SQL Editor once.
-- Creates a chat table for two allowed accounts: 白白 / 飞飞.
-- Supports text messages, image messages, and audio messages.

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  sender text not null,
  type text not null default 'text',
  content text not null default '',
  image_url text,
  audio_url text,
  audio_mime text,
  audio_duration_ms integer,
  reply_to_message_id bigint,
  reply_to_sender text,
  reply_to_type text,
  reply_to_preview text,
  created_at timestamptz not null default now(),
  constraint chat_messages_sender_check check (sender in ('白白', '飞飞')),
  constraint chat_messages_type_check check (type in ('text', 'image', 'audio')),
  constraint chat_messages_reply_sender_check check (reply_to_sender is null or reply_to_sender in ('白白', '飞飞')),
  constraint chat_messages_reply_type_check check (reply_to_type is null or reply_to_type in ('text', 'image', 'audio')),
  constraint chat_messages_payload_check check (
    (type = 'text' and char_length(trim(content)) > 0)
    or
    (type = 'image' and image_url is not null and image_url <> '')
    or
    (type = 'audio' and audio_url is not null and audio_url <> '')
  ),
  constraint chat_messages_reply_payload_check check (
    (
      reply_to_message_id is null
      and reply_to_sender is null
      and reply_to_type is null
      and reply_to_preview is null
    )
    or
    (
      reply_to_message_id is not null
      and reply_to_sender in ('白白', '飞飞')
      and reply_to_type in ('text', 'image', 'audio')
      and reply_to_preview is not null
    )
  )
);

alter table public.chat_messages enable row level security;

create table if not exists public.chat_read_state (
  account text primary key,
  last_read_message_id bigint,
  updated_at timestamptz not null default now(),
  constraint chat_read_state_account_check check (account in ('白白', '飞飞'))
);

alter table public.chat_read_state enable row level security;

-- Allow public (anon) read for history.
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'chat_messages' and policyname = 'chat_messages_select_anon'
  ) then
    create policy chat_messages_select_anon
      on public.chat_messages
      for select
      to anon
      using (true);
  end if;
end $$;

-- Allow public (anon) insert for the two allowed senders.
-- Text messages must have non-empty content.
-- Image messages must have a non-empty image_url.
-- Audio messages must have a non-empty audio_url.
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'chat_messages' and policyname = 'chat_messages_insert_anon'
  ) then
    create policy chat_messages_insert_anon
      on public.chat_messages
      for insert
      to anon
      with check (
        sender in ('白白', '飞飞')
        and (
          (type = 'text' and char_length(trim(content)) > 0)
          or
          (type = 'image' and image_url is not null and image_url <> '')
          or
          (type = 'audio' and audio_url is not null and audio_url <> '')
        )
      );
  end if;
end $$;

-- Allow public (anon) read for read receipts.
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'chat_read_state' and policyname = 'chat_read_state_select_anon'
  ) then
    create policy chat_read_state_select_anon
      on public.chat_read_state
      for select
      to anon
      using (true);
  end if;
end $$;

-- Allow public (anon) insert/update for read receipt cursor.
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'chat_read_state' and policyname = 'chat_read_state_insert_anon'
  ) then
    create policy chat_read_state_insert_anon
      on public.chat_read_state
      for insert
      to anon
      with check (account in ('白白', '飞飞'));
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'chat_read_state' and policyname = 'chat_read_state_update_anon'
  ) then
    create policy chat_read_state_update_anon
      on public.chat_read_state
      for update
      to anon
      using (account in ('白白', '飞飞'))
      with check (account in ('白白', '飞飞'));
  end if;
end $$;

-- Index for recent-history query speed and upward pagination.
create index if not exists chat_messages_created_at_idx on public.chat_messages (created_at desc);
create index if not exists chat_read_state_updated_at_idx on public.chat_read_state (updated_at desc);

-- IMPORTANT:
-- 1. In Supabase dashboard, make sure Realtime is enabled for public.chat_messages.
-- 2. In Supabase dashboard, make sure Realtime is enabled for public.chat_read_state.
-- 3. If you use image uploads, also create a public Storage bucket named chat-images.
-- 4. If you use audio uploads, also create a public Storage bucket named chat-audios.
-- 5. Add storage policies for anon users on storage.objects for bucket_id in ('chat-images', 'chat-audios').
