-- Run this in Supabase SQL Editor once.
-- Creates a chat table for two allowed accounts: 白白 / 飞飞.

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  sender text not null,
  content text not null,
  created_at timestamptz not null default now(),
  constraint chat_messages_sender_check check (sender in ('白白', '飞飞')),
  constraint chat_messages_content_check check (char_length(trim(content)) > 0)
);

alter table public.chat_messages enable row level security;

-- Allow public (anon) read for history.
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'chat_messages' and policyname = 'chat_messages_select_anon'
  ) then
    create policy chat_messages_select_anon
      on public.chat_messages
      for select
      to anon
      using (true);
  end if;
end $$;

-- Allow public (anon) insert for the two allowed senders.
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'chat_messages' and policyname = 'chat_messages_insert_anon'
  ) then
    create policy chat_messages_insert_anon
      on public.chat_messages
      for insert
      to anon
      with check (sender in ('白白', '飞飞') and char_length(trim(content)) > 0);
  end if;
end $$;

-- Optional: index for recent-history query speed.
create index if not exists chat_messages_created_at_idx on public.chat_messages (created_at desc);

-- IMPORTANT: In Supabase dashboard, make sure Realtime is enabled for public.chat_messages.
